### ISSUE TITLE
大佬的，线上版本是真好看，我部署了一个，有点问题

### ISSUE THREAD

**Issue by iamiao** [GzhiYi/dandan-account#107]
我部署了一个，有点问题删除已记账会显示删除失败，请重试，得重新载入小程序，才会看到删除了记录

**Comment by GzhiYi** [comment]
把错误贴上来看看？应该是删除报错前端这边没刷新列表

**Comment by iamiao** [comment]
![image](https://user-images.githubusercontent.com/39727490/161222090-a9ba753d-067d-4185-aeb9-26ac7d459dec.png)
就是这样，我也不懂是不是报错

**Comment by GzhiYi** [comment]
查看 referenced 说明，需要增加一个 STAT 的集合

**Comment by GzhiYi** [comment]
需要看看删除接口返回的错误信息

**Comment by iamiao** [comment]
![image](https://user-images.githubusercontent.com/39727490/161224450-0edc3092-cd79-4af8-a83b-b0e86339080f.png)
这个可以看的到么

**Comment by iamiao** [comment]
![image](https://user-images.githubusercontent.com/39727490/161224670-db0628eb-1b39-4de8-911c-9bebc149b1ac.png)
点了删除只显示这2个

**Comment by GzhiYi** [comment]
看接口response

**Comment by iamiao** [comment]
我该怎么操作，查看接口response

**Comment by GzhiYi** [comment]
![image](https://user-images.githubusercontent.com/21136420/161226209-583945cf-0b9d-48cb-b73e-c1969b08f0c9.png)

**Comment by iamiao** [comment]
![image](https://user-images.githubusercontent.com/39727490/161226353-9940f87b-9982-4697-9a45-02e7c0fffd48.png)
嗯

**Comment by GzhiYi** [comment]
老哥如果没有web开发基础感觉不好说😭

**Comment by GzhiYi** [comment]
先自行摸索一下吧？

**Comment by iamiao** [comment]
![image](https://user-images.githubusercontent.com/39727490/161226702-9f627070-8aaf-40df-a647-c6a0436e3708.png)
大佬我确实是没经验，我业余的，本身是电气工程师，自己喜欢捣鼓一些，自己不会写，那我先再看看，谢谢大佬解答

**Comment by GzhiYi** [comment]
嗯嗯，能捣鼓出怎么解决这个错误基本上可以改不少代码内容了

**Comment by GzhiYi** [comment]
上面截图没有抛出日志到小程序段，要去云函数去log日志查看了。估计是某个地方报错了，可以试着catch一下

**Comment by iamiao** [comment]
嗯嗯，感谢大佬的耐心，我先自己找一找，也不能一直伸手，谢谢

**Comment by GzhiYi** [comment]
如果找到了问题，贴在这个issue上然后close了？

**Comment by iamiao** [comment]
有了个大体方向，我查资料也有头绪方向，可以的，我找到问题写上就close

**Comment by iamiao** [comment]
![image](https://user-images.githubusercontent.com/39727490/161364241-59d2a8da-12ab-435c-b49f-d31ed5020603.png)
1改-1就可以了

**Comment by GzhiYi** [comment]
我看代码是 1 的为啥截图是 -1 的？

**Comment by iamiao** [comment]
原来是1，不行，我改-1就可以了

**Comment by iamiao** [comment]
大佬可以close了，云函数account里面我删了await updateStat(oldNote.noteDate)，就好了

**Comment by GzhiYi** [comment]
统计在这个版本没用上，可以删除掉的。
