### ISSUE TITLE
大佬 你好

### ISSUE THREAD

**Issue by elvisz2016** [GzhiYi/dandan-account#46]
请问 云开发要怎么迁移呢？

**Comment by elvisz2016** [comment]
项目拷贝进去 在微信开发者工具都看不到云函数目录。
已经重新创建过云开发项目了。

**Comment by GzhiYi** [comment]
你可以直接clone仓库然后导入，appId不对的话可以用一个测试的appId。云函数需要上传到云端才能正常使用。

如果是数据表的字段不知道，可以看这个文件，里面有数据的字段，对应的创建就好了。
[戳](https://github.com/GzhiYi/dandan-account/blob/master/doc.md)
