### ISSUE TITLE
单单账单记录_账单表结构

### ISSUE THREAD

**Issue by guozf2018** [GzhiYi/dandan-account#49]
初拟表结构， 欢迎修改
Create Collection DANDAN_NOTE_ACCOUNT {
_id : 系统生成,
accountDate String (账单日期 yyyy-MM-dd)
income Double  (收入),
Expenditure Double  (支出),
netIncome Double  (净收入),
createTime Date (创建时间),
updateTime Date (修改时间),
openId String (用户ID)
}
/**
以下可支持修改当天的数据
可以通过聚合函数addField().match()匹配到对应的日期
year  String（年 yyyy）
month String (月 MM)
day String (日 dd)
*/

**Comment by GzhiYi** [comment]
集合名字不要取这个吧？
应该取一个贴合统计数据的名字：比如`DANDAN_NOTE_STAT`（代表统计图表数据）。
关于集合， @hequanb 有空一起看下是否可以。
另mongo数据库类型没有这么细分，你可以先新建集合后尝试添加一条记录看看类型。

**Comment by GzhiYi** [comment]
`DANDAN_NOTE_STAT`集合已经创建了。
为你们挥舞双手。
折线图的样式我也初步写好了。
😁

**Comment by hequanb** [comment]
改下名字 复议
