### ISSUE TITLE
导入之后编译出现问题

### ISSUE THREAD

**Issue by 653304872** [GzhiYi/dandan-account#77]
找不到对应的FunctionName.

**Comment by GzhiYi** [comment]
可以提供下错误的信息或者截图不？

**Comment by 653304872** [comment]
![QQ截图20201009095736](https://user-images.githubusercontent.com/54772542/95533519-f0793b80-0a15-11eb-823d-568993b1c793.png)
![QQ截图20201009095756](https://user-images.githubusercontent.com/54772542/95533536-fa02a380-0a15-11eb-8745-ea5628788129.png)
这是截图，请您帮忙看一下，完全按照文档步骤来的，还有分类数据不显示的问题

**Comment by GzhiYi** [comment]
看起来分类数据没有导入进去噢。
按照分类导入的这个issue导入试试？ #63 
导入完成之后记得创建空的集合，也就是mango表。
找不到functionName或许是没有把云函数部署好，你可以部署下云函数。

**Comment by GzhiYi** [comment]
注意看看这个步骤过程。
#69

**Comment by 653304872** [comment]
好的，谢谢！我先试试

**Comment by GzhiYi** [comment]
如果解决了，可以close这个issue。

**Comment by 653304872** [comment]
![QQ截图20201010102231](https://user-images.githubusercontent.com/54772542/95643566-8d090f80-0ae2-11eb-9f53-75ceb904c5ab.png)
请问这是什么问题呢？

**Comment by GzhiYi** [comment]
看一下错误信息？

**Comment by 653304872** [comment]
![Uploading QQ截图20201010102622.png…]()

**Comment by 653304872** [comment]
![QQ截图20201010102622](https://user-images.githubusercontent.com/54772542/95643656-1d475480-0ae3-11eb-9fe6-89a7ab82728d.png)

**Comment by GzhiYi** [comment]
看返回的信息，不是请求头参数之类的噢

**Comment by 653304872** [comment]
![QQ截图20201010102622](https://user-images.githubusercontent.com/54772542/95643798-1cfb8900-0ae4-11eb-9832-99e13debe580.png)

**Comment by 653304872** [comment]
![QQ截图20201010103147](https://user-images.githubusercontent.com/54772542/95643807-2be23b80-0ae4-11eb-9865-14d9736f2142.png)

**Comment by GzhiYi** [comment]
https://github.com/GzhiYi/dandan-account/blob/ed111f5df3980d3a128cf0258124b49c895dedec/miniprogram/app.js#L12
查看环境是否配置为自己的环境id

**Comment by 653304872** [comment]
![QQ截图20201010104015](https://user-images.githubusercontent.com/54772542/95643915-220d0800-0ae5-11eb-9cbe-58fc177c678c.png)
wojiu我就改了这一个id，还有其他要改的嘛？

**Comment by GzhiYi** [comment]
https://github.com/GzhiYi/dandan-account/blob/master/INSTALL.md

**Comment by 653304872** [comment]
id就改了这一个地方，其他的也按照步骤弄了，可能是我云开发的问题，我先自己看看吧，麻烦你了，非常感谢！

**Comment by GzhiYi** [comment]
同步云函数 将cloudfunctions目录下所有文件夹都同步到云开发中的函数中去，点文件夹右键，上传并部署:云端安装依赖(不上传node_modules)
这一步做了吗？
如果有问题的话，解决了可以优化下部署文档的。

**Comment by GzhiYi** [comment]
你可以先摸索下问题出在哪，如果解决了，可以在这提出来，我看是否有需要对文档进行补充。

**Comment by 653304872** [comment]
之前的问题是我没把cloudfunctions目录下文件夹分别上传，现在还有一个新的问题，无法获取订单，这个上传不上去
![QQ截图20201010105820](https://user-images.githubusercontent.com/54772542/95644221-b7a99700-0ae7-11eb-93eb-f56e33f143a7.png)
![QQ截图20201010110037](https://user-images.githubusercontent.com/54772542/95644235-d9a31980-0ae7-11eb-8077-19ce80129c37.png)

**Comment by 653304872** [comment]
![QQ截图20201010110922](https://user-images.githubusercontent.com/54772542/95644415-1b808f80-0ae9-11eb-9910-14efe7c7fcc6.png)
这是错误信息

**Comment by hequanb** [comment]
接口返回信息是什么, 看看network这次请求的返回信息

**Comment by GzhiYi** [comment]
这确实是之前都未遇到过的问题。
现在是卡在了云函数部署到云端这一步上。我搜索了相关的问题，没有找到符合的答案。
你可以想办法试试重新上传云函数，实在无法判断问题原因，可以重新clone一份新代码再导入到开发工具上。

**Comment by GzhiYi** [comment]
> 接口返回信息是什么, 看看network这次请求的返回信息

云函数未部署成功，基本上返回的内容无法参考，并不是云函数执行错误导致的。

**Comment by 653304872** [comment]
重新clone一份新代码我试了，还是无法获取账单的问题

**Comment by GzhiYi** [comment]
pull 一下master代码再部署看看？
移除了AccountAgree这个无用的云函数。

**Comment by 653304872** [comment]
![QQ截图20201011101003](https://user-images.githubusercontent.com/54772542/95668686-f56ef400-0ba9-11eb-965d-289fbe34d6db.png)
账单还是显示不出来，并且有这个错误提示

**Comment by GzhiYi** [comment]
这个错误可以定位到哪个文件哪一行不？

**Comment by 653304872** [comment]
定位不到，创建账单的时候也创建不成功
![QQ截图20201012105953](https://user-images.githubusercontent.com/54772542/95700668-32a2b700-0c7a-11eb-92d3-3e4858cee02d.png)

**Comment by hequanb** [comment]
> 定位不到，创建账单的时候也创建不成功
> ![QQ截图20201012105953](https://user-images.githubusercontent.com/54772542/95700668-32a2b700-0c7a-11eb-92d3-3e4858cee02d.png)

可以看看你目前初始化的数据库的集合有哪些吗

**Comment by 653304872** [comment]
> > 定位不到，创造账单的时候也创造不成功
> > ![QQ截图20201012105953](https://user-images.githubusercontent.com/54772542/95700668-32a2b700-0c7a-11eb-92d3-3e4858cee02d.png)
> 
> 可以看看你目前初始化的数据库的集合有哪些吗

![QQ截图20201012145716](https://user-images.githubusercontent.com/54772542/95714799-562a2980-0c9b-11eb-980f-953d72673c09.png)
这是我根据文档提示创建的，不知道对不对，您给看看？

**Comment by hequanb** [comment]
我们这边部署文档写漏了, 你试试新建这几个集合

**Comment by 653304872** [comment]
> TARGET

![QQ截图20201012153348](https://user-images.githubusercontent.com/54772542/95718070-845e3800-0ca0-11eb-87b8-6a203274e1b6.png)
终于成功了，非常感谢！

**Comment by hequanb** [comment]
后续有问题 再说下好了,先关了

**Comment by 544211707** [comment]
> 之前的问题是我没把cloudfunctions目录下文件夹分别上传，现在还有一个新的问题，无法获取订单，这个上传不上去
> ![QQ截图20201010105820](https://user-images.githubusercontent.com/54772542/95644221-b7a99700-0ae7-11eb-93eb-f56e33f143a7.png)
> ![QQ截图20201010110037](https://user-images.githubusercontent.com/54772542/95644235-d9a31980-0ae7-11eb-8077-19ce80129c37.png)

确实，我也是有这个问题，原来是需要每个上传。我以为是直接选中`cloudfunctions`文件夹上传

**Comment by GzhiYi** [comment]
@544211707 可以到云开发后台查看云函数是否上传成功。

**Comment by 544211707** [comment]
> @544211707 可以到云开发后台查看云函数是否上传成功。

学到了 感谢大佬~
