### ISSUE TITLE
如果想以家庭为单位记账现在能实现吗

### ISSUE THREAD

**Issue by AndiSandy** [GzhiYi/dandan-account#83]
如题，比如我家里多个用户，想记在一起，就是数据互享，有什么简便的方法改造呢。我是后端开发，前端不太了解

**Comment by GzhiYi** [comment]
可以实现，可以协助看看这样的构思。我在这个issue有写了下一个版本的规划。 #81

**Comment by GzhiYi** [comment]
打算不加入这个功能了，写起来东西比较多。哭唧唧
