### ISSUE TITLE
在search页面可以对找到的账单信息进行编辑吗？

### ISSUE THREAD

**Issue by 12mmmjkl** [GzhiYi/dandan-account#87]
在search的json那里引入dialog发现不能使用。这是什么问题呢？

**Comment by GzhiYi** [comment]
可以贴出具体的代码信息看看？

**Comment by 12mmmjkl** [comment]
像这样，在查询页面，对于找到的账单数据点击是没有弹出编辑选项的。
原来的search的wxml里没有引入dialog
<dialog&nbsp;visible="{{showMenuDialog}}"&nbsp;bind:closeDialog="closeDialog"&gt;
&nbsp;&nbsp;&nbsp;&nbsp;<view&nbsp;slot="content"&gt;
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<view&nbsp;class="pop-indicator"&gt;</view&gt;
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<view&nbsp;class="d-header"&gt;
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{{editItem.category.categoryName}}
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<view&nbsp;class="dialog-tip"&gt;金额：{{editItem.flow&nbsp;===&nbsp;0&nbsp;?&nbsp;'-'&nbsp;:&nbsp;'+'}}{{editItem.money}}，记账日期：{{editItem.noteDate}}</view&gt;
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<view&nbsp;class="dialog-tip"&nbsp;wx:if="{{editItem.description}}"&gt;备注：{{editItem.description}}</view&gt;
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</view&gt;
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<view&nbsp;class='list-item-btn'&nbsp;style="color:&nbsp;#4fd69c;"&nbsp;bindtap="editBill"&gt;编辑</view&gt;
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<view&nbsp;class='list-item-btn'&nbsp;style="color:&nbsp;#f75676;"&nbsp;bindtap="deleteBill"&gt;
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{{showConfirmDelete&nbsp;?&nbsp;'再次点击确认删除'&nbsp;:&nbsp;'删除'}}
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</view&gt;
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<view&nbsp;class='list-item-btn'&nbsp;bindtap="closeDialog"&nbsp;style="border-bottom:&nbsp;none;"&gt;取消</view&gt;
&nbsp;&nbsp;&nbsp;&nbsp;</view&gt;
&nbsp;&nbsp;</dialog&gt;


我cv这个发现不行


这是使用的代码
<nav
&nbsp;&nbsp;class="nav-instance"
&nbsp;&nbsp;showIcons="{{['back']}}"
&gt;</nav&gt;
<view&nbsp;class="search"&gt;
&nbsp;&nbsp;<view&nbsp;class="banner"&gt;
&nbsp;&nbsp;&nbsp;&nbsp;<view&nbsp;class="banner-show"&gt;
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<image
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;src="https://images.vrm.cn/2019/08/29/pig.png"
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;style="width:&nbsp;120rpx;height:&nbsp;120rpx;"
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;bindtap="resetSearch"
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&gt;</image&gt;
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<view&nbsp;class='pig-talk'&nbsp;wx:if="{{word}}"&nbsp;bindtap="resetSearch"&gt;
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<view&nbsp;class='word-tang-left'&gt;</view&gt;
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<view&nbsp;class='word-detail'&gt;{{word}}</view&gt;
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</view&gt;
&nbsp;&nbsp;&nbsp;&nbsp;</view&gt;
&nbsp;&nbsp;</view&gt;
&nbsp;&nbsp;<input
&nbsp;&nbsp;&nbsp;&nbsp;type="text"
&nbsp;&nbsp;&nbsp;&nbsp;class="search-input"
&nbsp;&nbsp;&nbsp;&nbsp;value="{{keyword}}"
&nbsp;&nbsp;&nbsp;&nbsp;bindinput="onInputChange"
&nbsp;&nbsp;&nbsp;&nbsp;auto-focus
&nbsp;&nbsp;&nbsp;&nbsp;focus="{{isFocus}}"
&nbsp;&nbsp;&nbsp;&nbsp;confirm-type="search"
&nbsp;&nbsp;&nbsp;&nbsp;bindconfirm='confirmTap'
&nbsp;&nbsp;/&gt;
</view&gt;
<view&nbsp;class="search-result"&gt;
&nbsp;&nbsp;<view&nbsp;class="place"&gt;</view&gt;
&nbsp;&nbsp;<scroll-view&nbsp;scroll-y="{{true}}"&nbsp;style="height:&nbsp;{{$.sysInfo.screenHeight&nbsp;-&nbsp;(($.sysInfo.screenHeight&nbsp;+&nbsp;442.49)&nbsp;/&nbsp;4.67)}}px;"&nbsp;class="bill-list"&gt;
&nbsp;&nbsp;&nbsp;&nbsp;<view&nbsp;class="empty-search"&nbsp;wx:if="{{isSearching}}"&gt;查询中...</view&gt;
&nbsp;&nbsp;&nbsp;&nbsp;<view&nbsp;class="empty-search"&nbsp;wx:if="{{billList.length&nbsp;===&nbsp;0&nbsp;&amp;&amp;&nbsp;!isSearching}}"&gt;没有找到账单(&nbsp;´･･)ﾉ(._.`)</view&gt;
&nbsp;&nbsp;&nbsp;&nbsp;<view
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;class="bill-item"
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;wx:for="{{billList}}"
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;wx:key="{{item._id}}"
&nbsp;&nbsp;&nbsp;&nbsp;&gt;
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<view&nbsp;class="type-date"&gt;
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<view&nbsp;class="type"&gt;{{item.category.categoryName}}</view&gt;
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<view&nbsp;class="description"&nbsp;wx:if="{{item.description}}"&gt;{{item.description}}</view&gt;
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</view&gt;
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<view&nbsp;class="money-date"&gt;
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<view&gt;
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<view&nbsp;class="money"&nbsp;style="color:&nbsp;{{&nbsp;item.flow&nbsp;===&nbsp;1&nbsp;?&nbsp;'#4fd69c;'&nbsp;:&nbsp;'#f75676;'}}"&gt;
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{{item.flow&nbsp;===&nbsp;0&nbsp;?&nbsp;'-'&nbsp;:&nbsp;'+'}}{{item.money}}
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</view&gt;
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<view&nbsp;class="date"&gt;{{item.noteDate}}</view&gt;
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</view&gt;
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</view&gt;
&nbsp;&nbsp;&nbsp;&nbsp;</view&gt;
&nbsp;&nbsp;</scroll-view&gt;
&nbsp;&nbsp;
</view&gt;
<dialog&nbsp;visible="{{showMenuDialog}}"&nbsp;bind:closeDialog="closeDialog"&gt;
&nbsp;&nbsp;&nbsp;&nbsp;<view&nbsp;slot="content"&gt;
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<view&nbsp;class="pop-indicator"&gt;</view&gt;
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<view&nbsp;class="d-header"&gt;
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{{editItem.category.categoryName}}
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<view&nbsp;class="dialog-tip"&gt;金额：{{editItem.flow&nbsp;===&nbsp;0&nbsp;?&nbsp;'-'&nbsp;:&nbsp;'+'}}{{editItem.money}}，记账日期：{{editItem.noteDate}}</view&gt;
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<view&nbsp;class="dialog-tip"&nbsp;wx:if="{{editItem.description}}"&gt;备注：{{editItem.description}}</view&gt;
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</view&gt;
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<view&nbsp;class='list-item-btn'&nbsp;style="color:&nbsp;#4fd69c;"&nbsp;bindtap="editBill"&gt;编辑</view&gt;
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<view&nbsp;class='list-item-btn'&nbsp;style="color:&nbsp;#f75676;"&nbsp;bindtap="deleteBill"&gt;
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{{showConfirmDelete&nbsp;?&nbsp;'再次点击确认删除'&nbsp;:&nbsp;'删除'}}
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</view&gt;
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<view&nbsp;class='list-item-btn'&nbsp;bindtap="closeDialog"&nbsp;style="border-bottom:&nbsp;none;"&gt;取消</view&gt;
&nbsp;&nbsp;&nbsp;&nbsp;</view&gt;
&nbsp;&nbsp;</dialog&gt;




import&nbsp;{&nbsp;strip&nbsp;}&nbsp;from&nbsp;'../../util'

const&nbsp;{&nbsp;importStore&nbsp;}&nbsp;=&nbsp;getApp()
const&nbsp;{&nbsp;create,&nbsp;store&nbsp;}&nbsp;=&nbsp;importStore
let&nbsp;isNotifyReset&nbsp;=&nbsp;false
create.Page(store,&nbsp;{
&nbsp;&nbsp;use:&nbsp;['sysInfo.screenHeight',&nbsp;'sysInfo.statusBarHeight'],
&nbsp;&nbsp;data:&nbsp;{
&nbsp;&nbsp;&nbsp;&nbsp;billList:&nbsp;null,
&nbsp;&nbsp;&nbsp;&nbsp;isSearching:&nbsp;false,
&nbsp;&nbsp;&nbsp;&nbsp;word:&nbsp;'',
&nbsp;&nbsp;&nbsp;&nbsp;isFocus:&nbsp;true,
&nbsp;&nbsp;&nbsp;&nbsp;keyword:&nbsp;'',
&nbsp;&nbsp;&nbsp;&nbsp;isSearched:&nbsp;false,
&nbsp;&nbsp;&nbsp;&nbsp;showMenuDialog:&nbsp;false,
&nbsp;&nbsp;&nbsp;&nbsp;editItem:&nbsp;{},
&nbsp;&nbsp;},
&nbsp;&nbsp;confirmTap()&nbsp;{
&nbsp;&nbsp;&nbsp;&nbsp;const&nbsp;{&nbsp;keyword&nbsp;}&nbsp;=&nbsp;this.data
&nbsp;&nbsp;&nbsp;&nbsp;const&nbsp;self&nbsp;=&nbsp;this
&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(!keyword&nbsp;||&nbsp;!keyword.trim())&nbsp;return

&nbsp;&nbsp;&nbsp;&nbsp;//&nbsp;查询操作
&nbsp;&nbsp;&nbsp;&nbsp;self.setData({
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;isSearching:&nbsp;true,
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;billList:&nbsp;[],
&nbsp;&nbsp;&nbsp;&nbsp;})
&nbsp;&nbsp;&nbsp;&nbsp;wx.cloud.callFunction({
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;name:&nbsp;'search',
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;data:&nbsp;{
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;keyWord:&nbsp;keyword,
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;},
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;success(res)&nbsp;{
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(res.result.code&nbsp;===&nbsp;1)&nbsp;{
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;const&nbsp;billList&nbsp;=&nbsp;res.result.data
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;let&nbsp;income&nbsp;=&nbsp;0
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;let&nbsp;pay&nbsp;=&nbsp;0
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;billList.forEach((bill)&nbsp;=&gt;&nbsp;{
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(Number(bill.flow)&nbsp;===&nbsp;0)&nbsp;pay&nbsp;+=&nbsp;bill.money
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(Number(bill.flow)&nbsp;===&nbsp;1)&nbsp;income&nbsp;+=&nbsp;bill.money
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;})
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;self.setData({
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;billList,
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;isSearched:&nbsp;true,
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;word:&nbsp;`关键字&nbsp;${keyword}&nbsp;搜索结果：收入共：${strip(income)}，支出共：${strip(pay)}`,
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;})
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;}
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;},
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;fail()&nbsp;{
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;getApp().showError('查询出错，要不稍后再试😢')
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;},
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;complete()&nbsp;{
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;self.setData({
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;isSearching:&nbsp;false,
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;})
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;},
&nbsp;&nbsp;&nbsp;&nbsp;})
&nbsp;&nbsp;},
&nbsp;&nbsp;onInputChange(event)&nbsp;{
&nbsp;&nbsp;&nbsp;&nbsp;const&nbsp;{&nbsp;value&nbsp;}&nbsp;=&nbsp;event.detail
&nbsp;&nbsp;&nbsp;&nbsp;const&nbsp;{&nbsp;word&nbsp;}&nbsp;=&nbsp;this.data
&nbsp;&nbsp;&nbsp;&nbsp;//&nbsp;做判断，如果输入文字并且还没搜索出结果就提示重置
&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(value&nbsp;&amp;&amp;&nbsp;word&nbsp;!==&nbsp;'点猪重置输入哦～'&nbsp;&amp;&amp;&nbsp;!isNotifyReset)&nbsp;{
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;this.setData({
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;word:&nbsp;'点猪重置输入哦～',
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;isSearched:&nbsp;false,
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;})
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;isNotifyReset&nbsp;=&nbsp;true
&nbsp;&nbsp;&nbsp;&nbsp;}
&nbsp;&nbsp;&nbsp;&nbsp;this.setData({
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;keyword:&nbsp;value,
&nbsp;&nbsp;&nbsp;&nbsp;})
&nbsp;&nbsp;},
&nbsp;&nbsp;resetSearch()&nbsp;{
&nbsp;&nbsp;&nbsp;&nbsp;this.setData({
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;keyword:&nbsp;'',
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;word:&nbsp;'',
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;isFocus:&nbsp;true,
&nbsp;&nbsp;&nbsp;&nbsp;})
&nbsp;&nbsp;},
})



json：
{
&nbsp;&nbsp;"component":&nbsp;true,
&nbsp;&nbsp;"usingComponents":&nbsp;{
&nbsp;&nbsp;&nbsp;&nbsp;"dialog":&nbsp;"../dialog/dialog"
&nbsp;&nbsp;}
}


css：
page&nbsp;{
&nbsp;&nbsp;background-color:&nbsp;#e1dbff;
}
.banner&nbsp;{
&nbsp;&nbsp;width:&nbsp;100%;
&nbsp;&nbsp;display:&nbsp;flex;
&nbsp;&nbsp;justify-content:&nbsp;center;
&nbsp;&nbsp;align-items:&nbsp;center;
}

.banner-show&nbsp;{
&nbsp;&nbsp;display:&nbsp;flex;
&nbsp;&nbsp;align-items:&nbsp;center;
&nbsp;&nbsp;margin-bottom:&nbsp;20rpx;
}

.pig-talk&nbsp;{
&nbsp;&nbsp;display:&nbsp;flex;
&nbsp;&nbsp;align-items:&nbsp;center;
&nbsp;&nbsp;padding:&nbsp;14rpx&nbsp;0;
&nbsp;&nbsp;justify-content:&nbsp;center;
&nbsp;&nbsp;margin-left:&nbsp;27rpx;
}

.word-tang-left&nbsp;{
&nbsp;&nbsp;width:&nbsp;0;
&nbsp;&nbsp;height:&nbsp;0;
&nbsp;&nbsp;border-bottom:&nbsp;10px&nbsp;solid&nbsp;rgba(255,&nbsp;142,&nbsp;142,&nbsp;0.8);
&nbsp;&nbsp;border-left:&nbsp;10px&nbsp;solid&nbsp;transparent;
}

.word-detail&nbsp;{
&nbsp;&nbsp;max-width:&nbsp;500rpx;
&nbsp;&nbsp;font-size:&nbsp;25rpx;
&nbsp;&nbsp;background-color:&nbsp;rgba(255,&nbsp;142,&nbsp;142,&nbsp;0.8);
&nbsp;&nbsp;padding:&nbsp;9px;
&nbsp;&nbsp;border-radius:&nbsp;24rpx;
&nbsp;&nbsp;word-break:&nbsp;break-all;
&nbsp;&nbsp;word-wrap:&nbsp;break-word;
&nbsp;&nbsp;overflow:&nbsp;hidden;
&nbsp;&nbsp;text-align:&nbsp;left;
}
.search&nbsp;{
&nbsp;&nbsp;text-align:&nbsp;center;
&nbsp;&nbsp;position:&nbsp;fixed;
&nbsp;&nbsp;width:&nbsp;100%;
}
.search-input&nbsp;{
&nbsp;&nbsp;background-color:&nbsp;#6147ff;
&nbsp;&nbsp;height:&nbsp;80rpx;
&nbsp;&nbsp;border-radius:&nbsp;26rpx;
&nbsp;&nbsp;width:&nbsp;72%;
&nbsp;&nbsp;margin:&nbsp;0&nbsp;auto;
&nbsp;&nbsp;color:&nbsp;#fff;
&nbsp;&nbsp;padding:&nbsp;0&nbsp;30rpx;
&nbsp;&nbsp;font-weight:&nbsp;bold;
&nbsp;&nbsp;box-shadow:&nbsp;0px&nbsp;10px&nbsp;13px&nbsp;4px&nbsp;#b0a5ff;
}
.bill-item&nbsp;{
&nbsp;&nbsp;display:&nbsp;flex;
&nbsp;&nbsp;justify-content:&nbsp;space-between;
&nbsp;&nbsp;align-items:&nbsp;center;
&nbsp;&nbsp;margin:&nbsp;20rpx&nbsp;30rpx;
&nbsp;&nbsp;padding:&nbsp;20rpx&nbsp;30rpx;
&nbsp;&nbsp;background-color:&nbsp;#fff;
&nbsp;&nbsp;border-radius:&nbsp;14rpx;
}
.date&nbsp;{
&nbsp;&nbsp;color:&nbsp;#ccc;
&nbsp;&nbsp;font-size:&nbsp;25rpx;
&nbsp;&nbsp;text-align:&nbsp;right;
&nbsp;&nbsp;min-width:&nbsp;140rpx;
}
.type&nbsp;{
&nbsp;&nbsp;background:&nbsp;#5e72e4;
&nbsp;&nbsp;color:&nbsp;#fff;
&nbsp;&nbsp;border-radius:&nbsp;7rpx;
&nbsp;&nbsp;font-size:&nbsp;22rpx;
&nbsp;&nbsp;padding:&nbsp;5rpx&nbsp;10rpx;
&nbsp;&nbsp;width:&nbsp;fit-content;
&nbsp;&nbsp;margin-top:&nbsp;3rpx;
}
.money&nbsp;{
&nbsp;&nbsp;font-size:&nbsp;42rpx;
&nbsp;&nbsp;text-align:&nbsp;right;
}
.description&nbsp;{
&nbsp;&nbsp;font-size:&nbsp;27rpx;
&nbsp;&nbsp;margin:&nbsp;13rpx&nbsp;0&nbsp;0;
}
.place&nbsp;{
&nbsp;&nbsp;width:&nbsp;100%;
&nbsp;&nbsp;height:&nbsp;281rpx;
}
.empty-search&nbsp;{
&nbsp;&nbsp;font-size:&nbsp;28rpx;
&nbsp;&nbsp;color:&nbsp;grey;
&nbsp;&nbsp;text-align:&nbsp;center;
&nbsp;&nbsp;margin-top:&nbsp;70px;
}





你好，还想请教一个问题
饼图统计可以设置成统计一整年的吗？



-----------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "GzhiYi/dandan-account"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年3月17日(星期三) 中午1:38
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [GzhiYi/dandan-account] 在search页面可以对找到的账单信息进行编辑吗？ (#87)





 
可以贴出具体的代码信息看看？

**Comment by GzhiYi** [comment]
我在搜索结果的项目上未加入编辑功能，急用的话可以通过时间筛选找到对应的账单进行编辑。后续考虑增加这个功能。如果你可以写的话，也可以新增这个功能。和历史账单的操作一致，通过id去修改账单的信息就好了。

饼图统计暂时不能统计一年的。

**Comment by 12mmmjkl** [comment]
好的，谢谢你




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年3月22日(星期一) 上午10:34
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [GzhiYi/dandan-account] 在search页面可以对找到的账单信息进行编辑吗？ (#87)





 
我在搜索结果的项目上未加入编辑功能，急用的话可以通过时间筛选找到对应的账单进行编辑。后续考虑增加这个功能。如果你可以写的话，也可以新增这个功能。和历史账单的操作一致，通过id去修改账单的信息就好了。
 
饼图统计暂时不能统计一年的。
